# Generated by Django 6.1 on 2026-08-17 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="owner",
        ),
    ]
