# Generated by Django 6.1 on 2026-08-17 20:49

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


def migrate_opponents(apps, schema_editor):
    match_model = apps.get_model("tracker", "Match")
    team_model = apps.get_model("tracker", "Team")
    for match in match_model.objects.all():
        name = match.opponent_name.strip()
        team = team_model.objects.filter(name__iexact=name).first()
        if team is None:
            team = team_model.objects.create(name=name)
        match.opponent = team
        match.save(update_fields=["opponent"])


def restore_opponent_names(apps, schema_editor):
    match_model = apps.get_model("tracker", "Match")
    for match in match_model.objects.select_related("opponent"):
        match.opponent_name = match.opponent.name
        match.save(update_fields=["opponent_name"])


class Migration(migrations.Migration):
    dependencies = [("tracker", "0002_remove_match_owner")]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_player_name_case_insensitive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_team_name_case_insensitive",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="match",
            name="opponent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="tracker.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="opponent_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(migrate_opponents, restore_opponent_names),
        migrations.AlterField(
            model_name="match",
            name="opponent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="tracker.team",
            ),
        ),
        migrations.RemoveField(model_name="match", name="opponent_name"),
        migrations.AddField(
            model_name="scoreevent",
            name="scorer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="score_events",
                to="tracker.player",
            ),
        ),
        migrations.CreateModel(
            name="PositionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=50)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_events",
                        to="tracker.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_events",
                        to="tracker.player",
                    ),
                ),
            ],
            options={"ordering": ["-recorded_at", "-pk"]},
        ),
    ]
