# Generated by Django 6.1 on 2026-09-01

import datetime

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

SEASON_NAME = "2026-2027"
AGE_GROUP = "U11"


def expand_match_domain(apps, schema_editor):
    club_model = apps.get_model("tracker", "Club")
    season_model = apps.get_model("tracker", "Season")
    team_model = apps.get_model("tracker", "Team")
    match_model = apps.get_model("tracker", "Match")
    player_model = apps.get_model("tracker", "Player")
    membership_model = apps.get_model("tracker", "TeamMembership")
    preference_model = apps.get_model("tracker", "UserPreference")
    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    season, _ = season_model.objects.get_or_create(
        name=SEASON_NAME,
        defaults={
            "start_date": datetime.date(2026, 7, 1),
            "end_date": datetime.date(2027, 6, 30),
        },
    )
    legacy_names = {team.pk: team.name.strip() for team in team_model.objects.all()}
    for team_id, name in legacy_names.items():
        club = club_model.objects.filter(name__iexact=name).first()
        if club is None:
            club = club_model.objects.create(name=name)
        team_model.objects.filter(pk=team_id).update(
            club=club,
            season=season,
            age_group=AGE_GROUP,
            designation="",
        )

    primary_club = club_model.objects.filter(
        name__iexact=settings.PRIMARY_CLUB_NAME
    ).first()
    if primary_club is None:
        primary_club = club_model.objects.create(name=settings.PRIMARY_CLUB_NAME)
    primary_team, _ = team_model.objects.get_or_create(
        club=primary_club,
        season=season,
        age_group=AGE_GROUP,
        designation="",
        defaults={"name": settings.PRIMARY_CLUB_NAME},
    )

    today = datetime.date.today()
    for match in match_model.objects.all():
        if match.is_home:
            home_team_id = primary_team.pk
            away_team_id = match.opponent_id
        else:
            home_team_id = match.opponent_id
            away_team_id = primary_team.pk
        match_model.objects.filter(pk=match.pk).update(
            home_team_id=home_team_id,
            away_team_id=away_team_id,
            status="finished" if match.match_date <= today else "scheduled",
        )

    membership_model.objects.bulk_create(
        [
            membership_model(player_id=player.pk, team_id=primary_team.pk)
            for player in player_model.objects.all()
        ],
        ignore_conflicts=True,
    )
    preference_model.objects.bulk_create(
        [
            preference_model(user_id=user.pk, default_team_id=primary_team.pk)
            for user in user_model.objects.all()
        ],
        ignore_conflicts=True,
    )


def restore_match_domain(apps, schema_editor):
    club_model = apps.get_model("tracker", "Club")
    team_model = apps.get_model("tracker", "Team")
    match_model = apps.get_model("tracker", "Match")
    primary_club = club_model.objects.filter(
        name__iexact=settings.PRIMARY_CLUB_NAME
    ).first()

    for team in team_model.objects.select_related("club"):
        team_model.objects.filter(pk=team.pk).update(name=team.club.name)
    for match in match_model.objects.all():
        home_is_primary = (
            primary_club is not None and match.home_team.club_id == primary_club.pk
        )
        match_model.objects.filter(pk=match.pk).update(
            opponent_id=match.away_team_id if home_is_primary else match.home_team_id,
            is_home=home_is_primary,
        )


class Migration(migrations.Migration):
    dependencies = [("tracker", "0003_match_enhancements")]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_club_name_case_insensitive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={"ordering": ["-start_date", "-pk"]},
        ),
        migrations.AddField(
            model_name="team",
            name="age_group",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="designation",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="team",
            name="club",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="tracker.club",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="tracker.season",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="away_matches",
                to="tracker.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="home_matches",
                to="tracker.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("live", "Live"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="scoreevent",
            name="occurred_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tracker.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tracker.team",
                    ),
                ),
            ],
            options={
                "ordering": ["team", "player"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "team"), name="unique_team_membership"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="teams",
            field=models.ManyToManyField(
                related_name="players",
                through="tracker.TeamMembership",
                to="tracker.team",
            ),
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_preferences",
                        to="tracker.team",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goalkeepr_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(expand_match_domain, restore_match_domain),
        migrations.AlterField(
            model_name="team",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="tracker.club",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="tracker.season",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="away_matches",
                to="tracker.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="home_matches",
                to="tracker.team",
            ),
        ),
        migrations.RemoveField(model_name="match", name="opponent"),
        migrations.RemoveField(model_name="match", name="is_home"),
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_team_name_case_insensitive",
        ),
        migrations.RemoveField(model_name="team", name="name"),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("club", "season", "age_group", "designation"),
                name="unique_team_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(("home_team", models.F("away_team")), _negated=True),
                name="match_teams_must_differ",
            ),
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["club__name", "age_group", "designation", "pk"]},
        ),
    ]
