# Generated by Django 6.1 on 2026-09-01

import datetime

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

SEASON_NAME = "2026-2027"
AGE_GROUP = "U11"
LEGACY_PRIMARY_CLUB_NAME = "K.F.C. Sparta Kolmont"
MIGRATION_DATE = datetime.date(2026, 9, 1)


def expand_match_domain(apps, schema_editor):
    club_model = apps.get_model("tracker", "Club")
    season_model = apps.get_model("tracker", "Season")
    team_model = apps.get_model("tracker", "Team")
    match_model = apps.get_model("tracker", "Match")
    player_model = apps.get_model("tracker", "Player")
    membership_model = apps.get_model("tracker", "TeamMembership")

    season, _ = season_model.objects.get_or_create(
        name=SEASON_NAME,
        defaults={
            "start_date": datetime.date(2026, 7, 1),
            "end_date": datetime.date(2027, 6, 30),
        },
    )
    legacy_names = {team.pk: team.name.strip() for team in team_model.objects.all()}
    for team_id, name in legacy_names.items():
        club_name = (
            f"{name} (opponent)"
            if name.casefold() == LEGACY_PRIMARY_CLUB_NAME.casefold()
            else name
        )
        club = club_model.objects.filter(name__iexact=club_name).first()
        if club is None:
            club = club_model.objects.create(name=club_name)
        team_model.objects.filter(pk=team_id).update(
            name=club_name,
            club=club,
            season=season,
            age_group=AGE_GROUP,
        )

    primary_club = club_model.objects.filter(
        name__iexact=LEGACY_PRIMARY_CLUB_NAME
    ).first()
    if primary_club is None:
        primary_club = club_model.objects.create(name=LEGACY_PRIMARY_CLUB_NAME)
    primary_team, _ = team_model.objects.get_or_create(
        club=primary_club,
        season=season,
        age_group=AGE_GROUP,
        defaults={"name": LEGACY_PRIMARY_CLUB_NAME},
    )
    season_model.objects.filter(pk=season.pk).update(default_team_id=primary_team.pk)

    for match in match_model.objects.all():
        if match.is_home:
            home_team_id = primary_team.pk
            away_team_id = match.opponent_id
        else:
            home_team_id = match.opponent_id
            away_team_id = primary_team.pk
        match_model.objects.filter(pk=match.pk).update(
            home_team_id=home_team_id,
            away_team_id=away_team_id,
            status=(
                "finished" if match.match_date <= MIGRATION_DATE else "scheduled"
            ),
        )

    membership_model.objects.bulk_create(
        [
            membership_model(player_id=player.pk, team_id=primary_team.pk)
            for player in player_model.objects.all()
        ],
        ignore_conflicts=True,
    )


def restore_match_domain(apps, schema_editor):
    club_model = apps.get_model("tracker", "Club")
    team_model = apps.get_model("tracker", "Team")
    match_model = apps.get_model("tracker", "Match")
    primary_club = club_model.objects.filter(
        name__iexact=LEGACY_PRIMARY_CLUB_NAME
    ).first()

    for team in team_model.objects.select_related("club"):
        team_model.objects.filter(pk=team.pk).update(name=team.club.name)
    for match in match_model.objects.all():
        home_is_primary = (
            primary_club is not None and match.home_team.club_id == primary_club.pk
        )
        match_model.objects.filter(pk=match.pk).update(
            opponent_id=match.away_team_id if home_is_primary else match.home_team_id,
            is_home=home_is_primary,
        )


def remove_generated_primary_team(apps, schema_editor):
    club_model = apps.get_model("tracker", "Club")
    season_model = apps.get_model("tracker", "Season")
    team_model = apps.get_model("tracker", "Team")
    primary_club = club_model.objects.filter(
        name__iexact=LEGACY_PRIMARY_CLUB_NAME
    ).first()
    if primary_club is None:
        return
    season_model.objects.filter(default_team__club=primary_club).update(
        default_team=None
    )
    team_model.objects.filter(club=primary_club).delete()


class Migration(migrations.Migration):
    dependencies = [("tracker", "0003_match_enhancements")]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_club_name_case_insensitive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={"ordering": ["-start_date", "-pk"]},
        ),
        migrations.AddField(
            model_name="team",
            name="age_group",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="club",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="tracker.club",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="tracker.season",
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="default_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tracker.team",
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            remove_generated_primary_team,
        ),
        migrations.AddField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="away_matches",
                to="tracker.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="home_matches",
                to="tracker.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("live", "Live"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="scoreevent",
            name="occurred_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tracker.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tracker.team",
                    ),
                ),
            ],
            options={
                "ordering": ["team", "player"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "team"), name="unique_team_membership"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="teams",
            field=models.ManyToManyField(
                related_name="players",
                through="tracker.TeamMembership",
                to="tracker.team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="opponent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="tracker.team",
            ),
        ),
        migrations.RunPython(expand_match_domain, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="team",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="tracker.club",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="tracker.season",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="away_matches",
                to="tracker.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="home_matches",
                to="tracker.team",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, restore_match_domain),
        migrations.RemoveField(model_name="match", name="opponent"),
        migrations.RemoveField(model_name="match", name="is_home"),
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_team_name_case_insensitive",
        ),
        migrations.RemoveField(model_name="team", name="name"),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("club", "season", "age_group"),
                name="unique_team_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(("home_team", models.F("away_team")), _negated=True),
                name="match_teams_must_differ",
            ),
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["club__name", "age_group", "pk"]},
        ),
    ]
