# Generated by Django 6.1 on 2026-09-06 19:26

import django.db.models.deletion
from django.db import migrations, models


def copy_season_default(apps, schema_editor):
    defaults_model = apps.get_model("tracker", "Defaults")
    season_model = apps.get_model("tracker", "Season")
    season = (
        season_model.objects.exclude(default_team=None)
        .order_by("-start_date", "-pk")
        .first()
    )
    if season is not None:
        defaults_model.objects.create(
            pk=1,
            default_season_id=season.pk,
            default_team_id=season.default_team_id,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_expand_match_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Defaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tracker.season",
                    ),
                ),
                (
                    "default_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tracker.team",
                    ),
                ),
            ],
        ),
        migrations.RunPython(copy_season_default, migrations.RunPython.noop),
    ]
