# Generated by Django 6.1 on 2026-09-06 20:59

import django.db.models.deletion
from django.db import migrations, models


def expand_managed_defaults(apps, schema_editor):
    defaults_model = apps.get_model("tracker", "Defaults")
    for defaults in defaults_model.objects.select_related("default_team"):
        if defaults.default_team_id is not None:
            defaults.default_club_id = defaults.default_team.club_id
            defaults.default_age_group = defaults.default_team.age_group
            defaults.save(update_fields=["default_club", "default_age_group"])


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaults",
            name="default_age_group",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="defaults",
            name="default_club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tracker.club",
            ),
        ),
        migrations.RunPython(expand_managed_defaults, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="defaults",
            name="default_team",
        ),
        migrations.RemoveField(
            model_name="season",
            name="default_team",
        ),
    ]
