# Generated by Django 6.1 on 2026-09-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_replace_age_group_with_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaults",
            name="default_season",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (2022, "2022-2023"),
                    (2023, "2023-2024"),
                    (2024, "2024-2025"),
                    (2025, "2025-2026"),
                    (2026, "2026-2027"),
                    (2027, "2027-2028"),
                    (2028, "2028-2029"),
                    (2029, "2029-2030"),
                    (2030, "2030-2031"),
                    (2031, "2031-2032"),
                    (2032, "2032-2033"),
                    (2033, "2033-2034"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="season",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2022, "2022-2023"),
                    (2023, "2023-2024"),
                    (2024, "2024-2025"),
                    (2025, "2025-2026"),
                    (2026, "2026-2027"),
                    (2027, "2027-2028"),
                    (2028, "2028-2029"),
                    (2029, "2029-2030"),
                    (2030, "2030-2031"),
                    (2031, "2031-2032"),
                    (2032, "2032-2033"),
                    (2033, "2033-2034"),
                ]
            ),
        ),
    ]
