# Generated by Django 6.1 on 2026-09-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_alter_defaults_default_season_alter_team_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoreevent",
            name="scorer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="score_events",
                to="tracker.player",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="tracker.player",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="tracker.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="defaults",
            constraint=models.CheckConstraint(
                condition=models.Q(("pk", 1)), name="single_defaults_record"
            ),
        ),
    ]
