# Generated by Django 6.1 on 2026-09-10 19:35

import django.db.models.deletion
from django.db import migrations, models


def populate_default_team(apps, schema_editor):
    Defaults = apps.get_model("tracker", "Defaults")
    Team = apps.get_model("tracker", "Team")
    for defaults in Defaults.objects.all():
        if (
            defaults.default_club_id is None
            or defaults.default_season is None
            or not defaults.default_age_group
        ):
            continue
        team = Team.objects.filter(
            club_id=defaults.default_club_id,
            season=defaults.default_season,
            age_group=defaults.default_age_group,
        ).first()
        if team is not None:
            defaults.default_team_id = team.pk
            defaults.save(update_fields=["default_team"])


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0009_alter_defaults_default_season_alter_team_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaults",
            name="default_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tracker.team",
            ),
        ),
        migrations.RunPython(populate_default_team, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="defaults",
            name="default_club",
        ),
        migrations.RemoveField(
            model_name="defaults",
            name="default_season",
        ),
        migrations.RemoveField(
            model_name="defaults",
            name="default_age_group",
        ),
        migrations.AlterField(
            model_name="scoreevent",
            name="scorer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="score_events",
                to="tracker.player",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="tracker.player",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="tracker.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="defaults",
            constraint=models.CheckConstraint(
                condition=models.Q(("pk", 1)), name="single_defaults_record"
            ),
        ),
    ]
